export interface FurnitureItem {
  id: string
  nome: string
  descricao: string
  categoria: string
  preco: number
  imagens: string[]
  fornecedor?: string // Added supplier/manufacturer field
  posicao: {
    x: number // percentage
    y: number // percentage
  }
  alternativas?: FurnitureItem[]
}

export interface Room {
  id: string
  nome: string
  descricao: string
  imagem: string
  moveis: FurnitureItem[]
}

export const roomsData: Room[] = [
  {
    id: "lounge",
    nome: "LOUNGE",
    descricao: "AMBIENTE MODERNO E ACOLHEDOR PARA RECEBER OS CLIENTES",
    imagem: "/space-lounge.png",
    moveis: [
      {
        id: "mesa-centro",
        nome: "Mesa de Centro - MUNKEBO",
        descricao: "Conjunto de 2 mesas de apoio folheadas em carvalho (L55xP55xA43cm; L45xP45xA40)cm)",
        categoria: "Mobiliário",
        preco: 36.58,
        imagens: ["/munkebo-1.png", "/munkebo-2.png"],
        fornecedor: "JYSK",
        posicao: { x: 40, y: 63 },
        alternativas: [
          {
            id: "mesa-centro-alt1",
            nome: "Mesa de Centro - SVENSTRUP",
            descricao: "Conjunto de 2 mesas brancas em MDP com pés em carvalho (L60xP60xA46cm; L50xP50xA40cm)",
            categoria: "Mobiliário",
            preco: 73.16,
            imagens: ["/svenstrup-1.png", "/svenstrup-2.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "mesa-centro-alt2",
            nome: "Mesa de Centro - MILEO",
            descricao: "Conjunto de 3 mesas de apoio brancas com pernas em madeira (L34xP34xA35cm; L46,5xP46,5xA40cm; L60xP60xA45cm)",
            categoria: "Mobiliário",
            preco: 44.72,
            imagens: ["/mileo-1.png", "/mileo-2.png"],
            fornecedor: "Homa",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "mesa-centro-alt3",
            nome: "Mesa de Centro - BAKKEBJERG",
            descricao: "Mesa de apoio branca com pés em madeira (L40xP40xA43cm)",
            categoria: "Mobiliário",
            preco: 20.33,
            imagens: ["/bakkebjerg-1.png", "/bakkebjerg-2.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "cadeirao",
        nome: "Cadeirão - UDSBJERG - Bege",
        descricao: "Cadeirão em tecido bege e pernas em madeira maciça. Assento e encosto em espuma (L66xP68xA84cm)",
        categoria: "Mobiliário",
        preco: 88.82,
        imagens: ["/udjsbjerg-1.png", "/udjsbjerg-2.png", "/udjsbjerg-3.png"],
        fornecedor: "JYSK",
        posicao: { x: 46, y: 55 },
        alternativas: [
          {
            id: "cadeirao-alt1",
            nome: "Cadeirão - UDSBJERG - Cinza",
            descricao:
              "Cadeirão em tecido cinzento e pernas em madeira maciça. Assento e encosto em espuma (L66xP68xA84cm)",
            categoria: "Mobiliário",
            preco: 88.62,
            imagens: ["/udjsbjerg-4.png", "/udjsbjerg-5.png", "/udjsbjerg-6.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeirao-alt2",
            nome: "Cadeirão - VISOCA",
            descricao:
              "Cadeirão VISOCA em tecido cinza, com pés em metal com acabamento à cor de madeira natural (L57xP61xA83cm)",
            categoria: "Mobiliário",
            preco: 72.36,
            imagens: ["/visoca-1.png", "/visoca-2.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeirao-alt3",
            nome: "Cadeirão - THORUP",
            descricao:
              "Cadeirão em tecido bege, com pés em metal com acabamento à cor de madeira natural. Assento e encosto em espuma (L65xP74xA74cm)",
            categoria: "Mobiliário",
            preco: 80.49,
            imagens: ["/thorup-1.png", "/thorup-2.png", "/thorup-3.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeirao-alt4",
            nome: "Cadeirão - RODES",
            descricao:
              "Cadeirão em tecido com o assento e encosto em espuma. Pernas em madeira maciça (L44xP44xA87cm)",
            categoria: "Mobiliário",
            preco: 96.75,
            imagens: ["/rodes-1.png"],
            fornecedor: "Homa",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "pavimento",
        nome: "Pavimento flutuante",
        descricao: "Egger Classic 8/32 EPL 208 - É uma reprodução de madeira muito natural em tons naturais quentes",
        categoria: "Materiais",
        preco: 16.90,
        imagens: ["/egger-1.png", "/egger-2.png"],
        fornecedor: "Paumarc",
        posicao: { x: 15, y: 78 },
      },
      {
        id: "tinta-azul",
        nome: "Azul Doutor Finanças",
        descricao: "Cinacryl Mate - RAL 5012, esmalte acrílico de alta qualidade (10 a 12L/m2) - 0.75L",
        categoria: "Materiais",
        preco: 10.78,
        imagens: ["/cinacryl-5012-1.png", "/cinacryl-5012-2.jpg"],
        fornecedor: "CIN",
        posicao: { x: 42, y: 20 },
      },
      {
        id: "tinta-branco",
        nome: "Branco Doutor Finanças",
        descricao: "Robbialac Stucomat - RAL 9010, tinta de qualidade profissional (10 a 15L/m2) - Ultra Mate - 1L",
        categoria: "Materiais",
        preco: 10.81,
        imagens: ["/stucomat-9010-1.png", "/stucomat-9010-2.jpg"],
        fornecedor: "Robbialac",
        posicao: { x: 90, y: 15 },
      },
      {
        id: "biombo",
        nome: "Biombo",
        descricao:
          "Estrutura em madeira maciça ou MDF revestido a melamina de cor carvalho natural (L174xP30xA200cm; L153xP30xA180cm; L113xP30xA200cm), com placas giratorias em PVC decoradas com vinil impresso",
        categoria: "Mobiliário",
        preco: 1250.0,
        imagens: ["/biombo-std.png"],
        fornecedor: "Doutor Finanças",
        posicao: { x: 31, y: 55 },
      },
      {
        id: "retroiluminado",
        nome: "Retroiluminado",
        descricao:
          "Estrutura em MDF pintado à cor azul RAL 5012 com acabamento mate e retroiluminado - neonled 6000K (L97xP2xA73cm)",
        categoria: "Mobiliário",
        preco: 600.0,
        imagens: ["/retroiluminado-1.png"],
        fornecedor: "Doutor Finanças",
        posicao: { x: 35, y: 35 },
      },
      {
        id: "logo",
        nome: "Logo",
        descricao:
          "Logotipo Doutor Finanças em PVC branco mate (L100xP1xA17cm)",
        categoria: "Mobiliário",
        preco: 75.0,
        imagens: ["/retroiluminado-1.png"],
        fornecedor: "Doutor Finanças",
        posicao: { x: 35, y: 25 },
      },
      {
        id: "ripado",
        nome: "Artens Ravik Oak",
        descricao: "Painel ripado em madeira Artens Ravik natural oak 30x260cm (34,99m2)",
        categoria: "Materiais",
        preco: 22.19,
        imagens: ["/artens-oak-1.png", "/artens-oak-2.png"],
        fornecedor: "Leroy Merlin",
        posicao: { x: 20, y: 20 },
        alternativas: [
          {
            id: "ripado-alt1",
            nome: "Artens Inari Oak",
            descricao: "Painel ripado em madeira Artens Inari natural oak 30x260cm (25.99m2)",
            categoria: "Materiais",
            preco: 82.42,
            imagens: ["/artens-inari-1.png", "/artens-inari-2.png"],
            fornecedor: "Leroy Merlin",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "bengaleiro",
        nome: "Bengaleiro - EKRAR",
        descricao: "Bengaleiro, branco, 169 cm.",
        categoria: "Decoração",
        preco: 16.25,
        imagens: ["/ekrar-1.jpg", "/ekrar-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 48, y: 40 },
      },
      {
        id: "aparador",
        nome: "Aparador - BESTA",
        descricao: "Aparador em MDF branco com portas (L120xP42xA74cm)",
        categoria: "Mobiliário",
        preco: 121.95,
        imagens: ["/besta-1.png", "/besta-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 3, y: 65 },
      },
      {
        id: "tapete",
        nome: "Tapete - KNARDRUP",
        descricao: "Tapete de pelo curto em fibra sintética (L160xP230xA1cm)",
        categoria: "Decoração",
        preco: 121.14,
        imagens: ["/knardrup-1.png", "/knardrup-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 42, y: 69 },
        alternativas: [
          {
            id: "tapete-alt1",
            nome: "Tapete - ESPIGA",
            descricao:
              "Tapete de tecido plano em poliéster (L160xP230xA1cm)",
            categoria: "Decoração",
            preco: 88.62,
            imagens: ["/espiga-1.png", "/espiga-2.png"],
            fornecedor: "Leroy Merlin",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "tapete-alt2",
            nome: "Tapete - LUCERNE",
            descricao:
              "Tapete de pelo curto em fibra recicladas e algodão (L140xP200xA1cm)",
            categoria: "Decoração",
            preco: 121.14,
            imagens: ["/lucerne-1.png", "/lucerne-2.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
    ],
  },
  {
    id: "sala de reunião",
    nome: "SALA DE REUNIÃO",
    descricao: "ESPAÇO RESERVADO, MODERNO E FUNCIONAL PARA TOMAR DECISÕES FINANCEIRAS",
    imagem: "/space-meeting-room.png",
    moveis: [
      {
        id: "mesa",
        nome: "Mesa -  DECOTIRSO - Oak (F)",
        descricao: "Mesa com tampo em melamina a emitar carvalho e pernas metálicas fechado branco (L100xP200xA74cm)",
        categoria: "Mobiliário",
        preco: 374.88,
        imagens: ["/mesa-decotirso-1.png"],
        fornecedor: "Decotirso",
        posicao: { x: 45, y: 64 },
        alternativas: [
          {
            id: "mesa-alt1",
            nome: "Mesa - DECOTIRSO - Branco (F)",
            descricao: "Mesa com tampo em melamina branco e pernas metálicas fechado branco (L100xP200xA74cm)",
            categoria: "Mobiliário",
            preco: 374.88,
            imagens: ["/mesa-decotirso-2.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "mesa-alt2",
            nome: "Mesa - DECOTIRSO - Oak",
            descricao: "Mesa com tampo em melamina branco e pernas metálicas branco (L100xP200xA74cm)",
            categoria: "Mobiliário",
            preco: 227.70,
            imagens: ["/mesa-decotirso-3.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "mesa-alt3",
            nome: "Mesa - DECOTIRSO - Branco",
            descricao: "Mesa com tampo em melamina branco e pernas metálicas branco (L100xP200xA74cm)",
            categoria: "Mobiliário",
            preco: 227.70,
            imagens: ["/mesa-decotirso-4.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "mesa-alt4",
            nome: "Mesa - LISANA",
            descricao: "Mesa de tampo em MDF branco e pernas em madeira maciça (L100xP180xA75cm)",
            categoria: "Mobiliário",
            preco: 276.41,
            imagens: ["/lisana-1.png", "/lisana-2.png"],
            fornecedor: "Beliani",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "candeeiro",
        nome: "Candeeiro - EUNOIA",
        descricao: "Iluminação de teto suspensa linear de LED em alumínio (L120xP4xA7cm)",
        categoria: "Decoração",
        preco: 39.76,
        imagens: ["/eunola-1.png", "/eunola-2.png", "/eunola-3.png"],
        fornecedor: "Sklum",
        posicao: { x: 45, y: 25 },
        alternativas: [
          {
            id: "candeeiro-alt1",
            nome: "Candeeiro - ASTLEY",
            descricao:"Iluminação de teto suspensa linear de LED em alumínio (L120xP6xA7cm)",
            categoria: "Decoração",
            preco: 48.74,
            imagens: ["/astley-1.png", "/astley-2.png", "/astley-3.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "candeeiro-alt2",
            nome: "Candeeiro - Wilen",
            descricao:"Iluminação de teto suspensa linear de LED em alumínio (L120xP3xA3cm)",
            categoria: "Decoração",
            preco: 52.80,
            imagens: ["/wilen-1.png", "/wilen-2.png", "/wilen-3.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "cadeira",
        nome: "Cadeira - GLAMM",
        descricao: "Cadeira em tecido com assento e encosto em espuma. Pernas em aço a imitar madeira",
        categoria: "Mobiliário",
        preco: 30.85,
        imagens: ["/glamm-1.png", "/glamm-2.png"],
        fornecedor: "Sklum",
        posicao: { x: 25, y: 68 },
        alternativas: [
          {
            id: "cadeira-alt1",
            nome: "Cadeira - KANA",
            descricao:"Cadeira em tecido com assento e encosto em espuma. Pernas em aço a imitar madeira",
            categoria: "Mobiliário",
            preco: 44.68,
            imagens: ["/kana-1.png", "/kana-2.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeira-alt2",
            nome: "Cadeira - DAPHNE",
            descricao:"Cadeira em tecido com assento e encosto em espuma. Pernas em aço a imitar madeira",
            categoria: "Mobiliário",
            preco: 197.18,
            imagens: ["/daphne-1.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "smart-tv",
        nome: "Smart TV - LG",
        descricao: "Smart TV LG 43UA7300 43 polegadas 4K Ultra HD (L95xP6xA56cm)",
        categoria: "Decoração",
        preco: 243.89,
        imagens: ["/lg-1.png", "/lg-2.png"],
        fornecedor: "Worten",
        posicao: { x: 20, y: 45 },
      },
      {
        id: "vidro",
        nome: "Vidro",
        descricao: "Vidro temperado 10mm com acessórios de fixação",
        categoria: "Materiais",
        preco: 170.00,
        imagens: ["/vidro.png"],
        fornecedor: "Virtualfloat",
        posicao: { x: 20, y: 15 },
      },
      {
        id: "moldura",
        nome: "Moldura - RODALM",
        descricao: "Moldura em MDF branco com a frente em plástico (L50xP3xA70cm)",
        categoria: "Decoração",
        preco: 10.57,
        imagens: ["/rodalm-1.png", "/rodalm-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 40, y: 45 },
      },
      {
        id: "candeeiro-de-pe",
        nome: "Candeeiro de pé - LAUTERS",
        descricao: "Candeeiro de pé em madeira de freixo com abajour branco (L62xP62xA151cm)",
        categoria: "Decoração",
        preco: 40.64,
        imagens: ["/lauters-1.png", "/lauters-2.png", "/lauters-3.png"],
        fornecedor: "IKEA",
        posicao: { x: 15, y: 70 },
        alternativas: [
          {
            id: "candeeiro-de-pe-alt1",
            nome: "Candeeiro de pé - RIPOD",
            descricao:"Candeeiro de pé em madeira com abajur em tecido bege (L54xP54xA151cm)",
            categoria: "Decoração",
            preco: 78.82,
            imagens: ["/ripod-1.png", "/ripod-2.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "candeeiro-de-pe-alt2",
            nome: "Candeeiro de pé - SIMONA",
            descricao:"Candeeiro de pé em madeira com abajur em tecido branco (L52xP52xA150cm)",
            categoria: "Decoração",
            preco: 89.39,
            imagens: ["/simona-1.png", "/simona-2.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "candeeiro-de-mesa",
        nome: "Candeeiro de mesa - FORSA",
        descricao: "Candeeiro de mesa em aço branco com braço ajustável (L15xP15xA35cm)",
        categoria: "Decoração",
        preco: 14.63,
        imagens: ["/forsa-1.png", "/forsa-2.png", "/forsa-3.png"],
        fornecedor: "IKEA",
        posicao: { x: 95, y: 60 },
        alternativas: [
          {
            id: "candeeiro-de-mesa-alt1",
            nome: "Candeeiro de mesa - DEYAN",
            descricao:"Candeeiro de secretária em madeira carvalho e aço branco (L15xP15xA63cm)",
            categoria: "Decoração",
            preco: 32.48,
            imagens: ["/deyan-1.png", "/deyan-2.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "secretaria",
        nome: "Secretária - TROTTEN 140",
        descricao: "Secretária em MDF branco com pernas em aço branco (L140xP80xA75cm)",
        categoria: "Mobiliário",
        preco: 80.49,
        imagens: ["/trotten-1.png", "/trotten-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 85, y: 65 },
        alternativas: [
          {
            id: "secretaria-alt1",
            nome: "Secretária - TROTTEN 120",
            descricao:"Secretária em MDF branco com pernas em aço branco (L120xP70xA75cm)",
            categoria: "Mobiliário",
            preco: 56.10,
            imagens: ["/trotten-3.png", "/trotten-4.png"],
            fornecedor: "IKEA",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "secretaria-alt2",
            nome: "Secretária - DECOTIRSO - Sem painel",
            descricao:"Secretária em melamina branco com pernas fechado em aço branco sem painel inferior (L140xP80xA74cm)",
            categoria: "Mobiliário",
            preco: 193.05,
            imagens: ["/sec-decotirso-1.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "secretaria-alt3",
            nome: "Secretária - DECOTIRSO - Com painel",
            descricao:"Secretária em melamina branco com pernas fechado em aço branco com painel inferior (L140xP80xA74cm)",
            categoria: "Mobiliário",
            preco: 213.68,
            imagens: ["/sec-decotirso-2.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "secretaria-alt4",
            nome: "Secretária - DECOTIRSO",
            descricao:"Secretária em melamina branco com pernas em aço branco (L140xP80xA74cm)",
            categoria: "Mobiliário",
            preco: 178.2,
            imagens: ["/sec-decotirso-3.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "cadeira-operativa",
        nome: "Cadeira operativa - TEILL - Cinza claro",
        descricao: "Cadeira de escritório de estrutura branca com rodas e apoios de braços em polipropileno. Costas em rede cinza claro (L62xP46xA105cm)",
        categoria: "Mobiliário",
        preco: 96.71,
        imagens: ["/teill-1.png", "/teill-2.png"],
        fornecedor: "Sklum",
        posicao: { x: 85, y: 60 },
        alternativas: [
          {
            id: "cadeira-operativa-alt1",
            nome: "Cadeira operativa - TEILL - Cinza escuro",
            descricao:"Cadeira de escritório de estrutura preta com rodas e apoios de braços em polipropileno. Costas em rede cinza (L62xP46xA105cm)",
            categoria: "Mobiliário",
            preco: 85.33,
            imagens: ["/teill-3.png", "/teill-4.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeira-operativa-alt2",
            nome: "Cadeira operativa - ORION",
            descricao:"Cadeira rodada com apoio de braço regulável. Costas em rede preta e assento em tecido ou pele sintética cinza com elevação a gás",
            categoria: "Mobiliário",
            preco: 156.75,
            imagens: ["/orion-1.png", "/orion-2.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "tapete",
        nome: "Tapete - KNARDRUP",
        descricao: "Tapete de pelo curto em fibra sintética (L160xP230xA1cm)",
        categoria: "Decoração",
        preco: 121.14,
        imagens: ["/knardrup-1.png", "/knardrup-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 75, y: 76 },
        alternativas: [
          {
            id: "tapete-alt1",
            nome: "Tapete - ESPIGA",
            descricao:
              "Tapete de tecido plano em poliéster (L160xP230xA1cm)",
            categoria: "Decoração",
            preco: 88.62,
            imagens: ["/espiga-1.png", "/espiga-2.png"],
            fornecedor: "Leroy Merlin",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "tapete-alt2",
            nome: "Tapete - LUCERNE",
            descricao:
              "Tapete de pelo curto em fibra recicladas e algodão (L140xP200xA1cm)",
            categoria: "Decoração",
            preco: 121.14,
            imagens: ["/lucerne-1.png", "/lucerne-2.png"],
            fornecedor: "JYSK",
            posicao: { x: 0, y: 0 },
          },
        ],
      }, 
    ],
  },
  {
    id: "open space",
    nome: "OPEN SPACE",
    descricao: "ACOLHEDOR, PRÁTICO E FOCADO NO CLIENTE",
    imagem: "/space-openspace.png",
    moveis: [
      {
        id: "cadeira-operativa",
        nome: "Cadeira operativa - TEILL - Cinza claro",
        descricao: "Cadeira de escritório de estrutura branca com rodas e apoios de braços em polipropileno. Costas em rede cinza claro (L62xP46xA105cm)",
        categoria: "Mobiliário",
        preco: 96.71,
        imagens: ["/teill-1.png", "/teill-2.png"],
        fornecedor: "Sklum",
        posicao: { x: 60, y: 60 },
        alternativas: [
          {
            id: "cadeira-operativa-alt1",
            nome: "Cadeira operativa - TEILL - Cinza escuro",
            descricao:"Cadeira de escritório de estrutura preta com rodas e apoios de braços em polipropileno. Costas em rede cinza (L62xP46xA105cm)",
            categoria: "Mobiliário",
            preco: 85.33,
            imagens: ["/teill-3.png", "/teill-4.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeira-operativa-alt2",
            nome: "Cadeira operativa - ORION",
            descricao:"Cadeira rodada com apoio de braço regulável. Costas em rede preta e assento em tecido ou pele sintética cinza com elevação a gás",
            categoria: "Mobiliário",
            preco: 156.75,
            imagens: ["/orion-1.png", "/orion-2.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "secretaria",
        nome: "Secretária - TROTTEN 140",
        descricao: "Secretária em MDF branco com pernas em aço branco (L140xP80xA75cm)",
        categoria: "Mobiliário",
        preco: 80.49,
        imagens: ["/trotten-1.png", "/trotten-2.png"],
        fornecedor: "IKEA",
        posicao: { x: 60, y: 75 },
        alternativas: [
          {
            id: "secretaria-alt1",
            nome: "Secretária - TROTTEN 120",
            descricao:"Secretária em MDF branco com pernas em aço branco (L120xP70xA75cm)",
            categoria: "Mobiliário",
            preco: 56.10,
            imagens: ["/trotten-3.png", "/trotten-4.png"],
            fornecedor: "IKEA",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "secretaria-alt2",
            nome: "Secretária - DECOTIRSO - Sem painel",
            descricao:"Secretária em MDF branco com pernas em aço branco sem painel inferior (L140xP80xA74cm)",
            categoria: "Mobiliário",
            preco: 193.05,
            imagens: ["/sec-decotirso-1.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "secretaria-alt3",
            nome: "Secretária - DECOTIRSO - Com painel",
            descricao:"Secretária em MDF branco com pernas em aço branco com painel inferior (L140xP80xA74cm)",
            categoria: "Mobiliário",
            preco: 213.68,
            imagens: ["/sec-decotirso-2.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "secretaria-alt4",
            nome: "Secretária - DECOTIRSO",
            descricao:"Secretária em melamina branco com pernas em aço branco (L140xP80xA74cm)",
            categoria: "Mobiliário",
            preco: 178.20,
            imagens: ["/sec-decotirso-3.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "cadeira",
        nome: "Cadeira - GLAMM",
        descricao: "Cadeira em tecido com assento e encosto em espuma. Pernas em aço a imitar madeira",
        categoria: "Mobiliário",
        preco: 30.85,
        imagens: ["/glamm-1.png", "/glamm-2.png"],
        fornecedor: "Sklum",
        posicao: { x: 40, y: 75 },
        alternativas: [
          {
            id: "cadeira-alt1",
            nome: "Cadeira - KANA",
            descricao:"Cadeira em tecido com assento e encosto em espuma. Pernas em aço a imitar madeira",
            categoria: "Mobiliário",
            preco: 44.67,
            imagens: ["/kana-1.png", "/kana-2.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
          {
            id: "cadeira-alt2",
            nome: "Cadeira - DAPHNE",
            descricao:"Cadeira em tecido com assento e encosto em espuma. Pernas em aço a imitar madeira",
            categoria: "Mobiliário",
            preco: 197.18,
            imagens: ["/daphne-1.png"],
            fornecedor: "Decotirso",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "candeeiro-de-mesa",
        nome: "Candeeiro de mesa - FORSA",
        descricao: "Candeeiro de mesa em aço branco com braço ajustável (L15xP15xA35cm)",
        categoria: "Decoração",
        preco: 14.63,
        imagens: ["/forsa-1.png", "/forsa-2.png", "/forsa-3.png"],
        fornecedor: "IKEA",
        posicao: { x: 25, y: 60 },
        alternativas: [
          {
            id: "candeeiro-de-mesa-alt1",
            nome: "Candeeiro de mesa - DEYAN",
            descricao:"Candeeiro de secretária em madeira carvalho e aço branco (L15xP15xA63cm)",
            categoria: "Decoração",
            preco: 32.48,
            imagens: ["/deyan-1.png", "/deyan-2.png"],
            fornecedor: "Sklum",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
      {
        id: "iluminacao",
        nome: "Iluminação - PERFIL LED",
        descricao: "Perfil em aluminio branco para fita LED 4000k (L100xP2xA0.8cm).",
        categoria: "Decoração",
        preco: 5.76,
        imagens: ["/perfil-led-1.png", "/perfil-led-2.png"],
        fornecedor: "Leroy Merlin",
        posicao: { x: 70, y: 20 },
        alternativas: [
          {
            id: "ilumincao-alt1",
            nome: "Iluminação - SPOT",
            descricao:"Spot embutido com LED 2200lm IP44 9.7W 4000k(L22.5xP22.5xA2cm)",
            categoria: "Decoração",
            preco: 14.63,
            imagens: ["/downlight-1.png", "/downlight-2.png"],
            fornecedor: "Leroy Merlin",
            posicao: { x: 0, y: 0 },
          },
        ],
      },
    ],
  },
]

export const furnitureData: FurnitureItem[] = roomsData[0].moveis
export const getRoomImage = () => roomsData[0].imagem

export interface CartItem extends FurnitureItem {
  quantidade: number
}
